[정렬, 맵, 셋] 2월 18일
Altu-Bitu-6/Altu-Bitu-WooJeongA pull request #1
Opened 2024-02-18 13:11 UTC by ktde24

### 인적사항
학번: 2176223
이름: 우정아
</br>

### 과제제출
기존 제출: 1431, 1946, 9375, 14425, 19636
추가 제출: 19636(수정)
</br>

2024-02-20 15:45 UTC, chae-jpg approved these changes
**[정렬, 맵, 셋 이론 코드리뷰 완료]**

1431(P3), 14425(P3)
정아님 안녕하세요! 코드 리뷰 완료되었습니다👍
함수 분리부터 주석처리까지 너무 깔끔하게 잘 풀어주셨어요!
도전 문제까지 모두 풀어주시다니 정말 멋져요! 수고하셨습니다👍👍
몇 가지 사소한 코멘트 남겼습니다!
궁금하신 점이 있다면 언제나 리뷰어를 호출해주세요😊

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +int sumNum(const string& s){
함수 분리 좋아요!

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +    for (char c : s){ // s 문자열 내의 문자를 돌면서
for-each문 깔끔합니다👍

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +bool cmp(const string& A, const string& B){
사용자 정의 정렬을 위해서 비교 함수를 잘 선언해주셨네요!

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/1431.cpp
> +    int N; // N: 기타 개수
P3
알튜비튜에서는 상수를 제외한 변수에는 스네이크 표기법을 권장하고 있어요!
다음부터는 이에 맞춰서 변수를 선언해주시면 완벽할 것 같습니다 💯

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +    unordered_set<string> S; // 집합 S를 저장할 해시 테이블
set보다도 탐색 시간이 짧은 unordered set을 사용해서 문제를 풀어주셨네요! 좋아요~

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +    int N, M, count = 0;
위와 마찬가지로 소문자로 선언해주시면 좋을 것 같아요!

2024-02-20 15:45 UTC, chae-jpg commented on 01_정렬_맵_셋/14425.cpp
> +    cout << count << endl; // 결과 출력
endl 대신 바로 '\n'처럼 개행문자를 출력하면 시간을 조금 줄일 수 있어요!

2024-02-21 12:15 UTC, kimhj010502 requested changes
**[정렬, 맵, 셋 구현 문제 코드 리뷰 완료]**

19636(P1)

정아님 안녕하세요!
과제하시느라 수고 많으셨습니다!! 👍
코드에 오류가 있으면 제출로 인정되지 않아요.
코드 수정 후 리뷰어를 재호출해주세요!

2024-02-21 12:15 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +int main() {
P2. 모든 연산을 main 함수에서 해주었네요~ 알튜비튜에서는 함수로 구현할 수 있는 부분은 최대한 함수를 따로 정의해서 사용하는 것을 권장하고 있어요! 다음부터는 함수화할 수 있는 부분이 있을지 고려해주세요!

2024-02-21 12:15 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +    cin >> W0 >> I0 >> T >> D >> I >> A;
P2. 변수 이름은 스네이크 표기법으로 정의해주세요!

2024-02-21 12:15 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +        cout << noChangeWeight << " " << I0 << endl; // 예상 체중 및 일일 기초 대사량 출력
줄바꿈 출력할 때 `endl`을 사용해도 좋은데 속도면에서 `\n`을 사용하는 것이 좀 더 빨라요!

2024-02-21 12:15 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +    for (int day = 0; day < D; ++day) {
`++day`로 작성한 이유가 있을까요? 보통은 `day++`로 작성해서 그렇게 작성하는게 가독성이 좋을 것 같아요!

2024-02-21 12:15 UTC, kimhj010502 commented on 01_정렬_맵_셋/19636.cpp
> +            changeI += energyDiff / 2; // 일일 기초 대사량 변화
P1. 이 부분 때문에 코드가 돌아가지 않네요..! 틀린 코드를 제출하는 것은 제출로 인정되지 않아요 샘플 답안 코드를 참고해서 수정한 후 추가제출 해주세요!

2024-02-22 00:36 UTC, ktde24 commented on 01_정렬_맵_셋/19636.cpp
> +            changeI += energyDiff / 2; // 일일 기초 대사량 변화
19636번 코드 수정 완료했습니다!

2024-03-10 08:34 UTC, merged